spring:
  datasource:
    username: root
    password: root1234
    url: jdbc:mysql://localhost:3306/book_toy?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        batch_fetch_style: dynamic
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


kakao:
  appkey: 91dcd7285ece2c9d52ad39b2f3f30137
  book:
    search:
      url: https://dapi.kakao.com/v3/search

feign:
  client:
    config:
      feignName:
        loggerLevel: FULL

logging:
  level:
    root: ERROR

    org:
      hibernate: info
      springframework:
        web: debug
        security: debug
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
